### ISSUE TITLE
Schedule Disbursements

### ISSUE THREAD

**Issue by wcorkill** [SFDO-Community/OutboundFunds#20]
Create a new interface to schedule disbursements in an automated fashion, similar to schedule payments and/or manage allocations

**Comment by wcorkill** [comment]
- [ ] Determine Rollups Needed
- [ ] What field(s) need to account for new Rollups
- [ ] What changes to interface code need to be made to account for pending disbursements
- [ ] Commit Code to Outbound Funds Core Package

**Comment by wcorkill** [comment]
Code has been committed to the branch.

### Work Completed

- Created New Rollup Field for Unpaid Disbursements
- Updated Total Disbursements formula field =  Awarded - Paid Disbursements - Unpaid Disbursements
- Updated field labels and descriptions on Total Remaining and Total Disbursed fields.

**Comment by Nickers3** [comment]
Can close issue as create disbursement branch has been merged into master.
