### ISSUE TITLE
Contact Roles

### ISSUE THREAD

**Issue by wcorkill** [SFDO-Community/OutboundFunds#21]
Consider creating a "Contact Roles" child object for Funding Requests

### Use Cases

> The org I am working with wants to automate the generation of their grant letters directly from Salesforce and as part of that, could have anywhere between 2 to 5+ contacts that would need to sign the document. So a contact role type of object would be best.

> In my use case we have many more people than just the one 'Organization Contact' that we need to track - for example, we need to know who the person is who can sign the grant letter, but other people often need to be cc'ed on the grant letter too. Also, just curious if anyone has done a DocuSign integration yet for their contracts for their awarded outbound funds

### Requirements
**Object Name**
- Funding Request Roles

**Fields**
- Contact (Lookup)
- Role (picklist)

**Comment by marktcoburn** [comment]
I've done CongaSign with this, used the standard contract object with a custom Conga Composer and Sign button. 

I think this idea is great, in particular, if we were able to add permissions for those folks who are added as contact roles, and who are also community users (against those contacts). This would be specific to the community scenario, but, this has come up a couple of times at our org.

**Comment by sharireily** [comment]
**Requirements**
https://docs.google.com/spreadsheets/d/1FYGOP1I4HTxnE5fzKTRhA_93uA5zYaEGirgpJZjdVAo/edit?usp=sharing
**Object Name**
Funding Request Role
Plural: Funding Request Roles
Activities - no
Report - yes
Search - yes 
Description: Tracks related Contacts on Funding Requests. 

**Fields**
Contact (Lookup)
Funding Request (master detail) 
Role (picklist: Grant Manager, Financial Manager, Applicant)
Status (picklist: Current, Former) 
Primary (Checkbox): would need to be enforced to only have one Primary Contact  

**Document:** 
How to enforce Only one primary contact, do not include in package.

**Comment by Nickers3** [comment]
Closing issue as funding request role branch has been merged into master.
