### ISSUE TITLE
Schedule GAU Expenditures

### ISSUE THREAD

**Issue by sharireily** [SFDO-Community/OutboundFunds#36]
### **Problem to Solve**
Reconcile incoming money with outgoing money (cash in/cash out)

### **User Stories and Use Cases**
**Use Case 1** 
As a grant manager, I can assign/update a disbursement to the appropriate funding bucket(s) at the time of the disbursement so that I can specify where the money should be pulled from.

- New button on Disbursement (located on the related list for GAU Expenditures) to “Manage Expenditures” to launch lightning component, similar to “Manage Allocations” (see below)

**Use Case 2**
As a grant manager, when assigning a disbursement to a funding bucket, I can choose either an amount or a percentage of the disbursement to assign so that it’s easier to split the disbursement to different funding buckets.

- In the “Manage Expenditures” lightning component (see above screenshot), show:

1. Lookup to General Accounting Unit
2. Percent field - if a valid percent is entered in this field, the amount should calculate dynamically based on percent x disbursement amount, and the amount field should grey out
3. Amount field - if a valid amount is entered in this field, the percent field should remain greyed out

**Use Case 3**
As a grant manager, I can remove incorrect assignments for a disbursement so that we don’t draw from the incorrect bucket.

- In the “Manage Expenditures” lightning component (see above screenshot), show per assignment:

1. Delete button - will remove the current line
2. Add Row button - will add a new blank line below the existing lines

**Use Case 4**
As a grant manager, when assigning a disbursement to multiple funding buckets, I can manage the different assignments in a single screen and see how much has already been assigned so that I do not assign more than 100% of the disbursement.

- In the “Manage Expenditures” lightning component (see above screenshot), show:

1. Disbursement amount (amount remaining that is not assigned to a GAU)
2. Dynamically change the disbursement amount as assignments to GAUs are made so that the user knows how much is left to assign
3. If the amount remaining is negative, then the value should be bolded and red. The “Save” button on the lightning component should be greyed out.
4. Display warning when user clicks “Save” if total amount of expenditures > disbursement amount (have to check this in case 2 people are creating expenditures for the same disbursement simultaneously)

**Use Case 5**
As a grant manager, when assigning a disbursement to funding bucket(s), I should not be able to proceed with the assignment if there aren’t sufficient funds in the bucket so that I do not draw from nonexistent funds.

- In the “Manage Expenditures” lightning component, show:

1. Available funds from selected General Accounting Units per line (add this as a separate column between “Percent” fields and “Delete” buttons)
2. Available funds = Total Allocations - Total Scheduled Disbursements - Total Paid Disbursements
3. Display warning for lines that have amount > available funds when user clicks “Save”

**Use Case 6**
As an accountant and a grant manager, I can see how much I have received and am projected to receive for a funding bucket, along with how much has been disbursed and will be disbursed, so that we know whether to approve/reject a disbursement request.

- Create rollups on the general accounting unit to show:

1. Total Paid Disbursements ($) - GAU Expenditures that are associated with “Paid” Disbursements
2. Total Scheduled Disbursements ($) - GAU Expenditures that are associated with Disbursements that are not “Paid” or “Cancelled”

**Use Case 7**
As a grant manager, I can specify a default funding bucket for a funding request so that I don’t have to do this individually for every disbursement.

- Enhance existing functionality of scheduling bulk disbursements (see below screenshot) to include creation of GAU expenditures

1. Add lookup to GAU on the Schedule Bulk Disbursements modal under Calculate Disbursements section (under “Interval”, above “Calculate” button)
2. If lookup to GAU is populated, then for every scheduled disbursement, create a GAU expenditure record to associate the disbursement to the selected GAU as 100% of the disbursement amount
3. If lookup to GAU is not populated, then no GAU expenditure records will be created

**Use Case 8**
As a grant manager, I want to see which donors contributed to a funding program so that I can report back to them on program success and how their money was used.

- Related list of GAU Expenditures on General Accounting Unit should display Funding Request column

**Use Case 9**
As a gift officer, I can specify the funding program that should receive the donation so that the grants manager knows how much is available for the funding program.

- If we assume that the GAU = Funding Program, then this is satisfied through GAU Allocation
- If NPSP is not being used, then [outside the Outbound Funds package] create a lookup to Funding Program on Opportunity
- If NPSP is being used, and the Opportunity could be related to multiple funding programs, then [outside the Outbound Funds package] create a junction between GAU and Funding Program

**Use Case 10**
As a grant manager, if I enter an error condition when I’m in the “Manage Expenditures” lightning component after I’ve clicked Save, I should have the ability to change/correct the data so that I don’t have re-enter everything.

- Error message displayed to user (if total expenditures > disbursement amount, or GAU has insufficient funds) should provide instructions on how to proceed successfully without clearing the entered data

### **Future Enhancements**

As a grant manager, I can specify multiple funding buckets for a funding request so that I can draw funds from different buckets.

**Comment by Nickers3** [comment]
This was delivered with the NPSP Expenditure package: [Pull Request](https://github.com/SFDO-Community/OutboundFundsNPSP/pull/13)
