### ISSUE TITLE
Link Funding Request Role to Disbursements and Requirements

### ISSUE THREAD

**Issue by Nickers3** [SFDO-Community/OutboundFunds#43]
It would be nice to have a way to link Funding Request Role to Disbursements and Requirements.  Ideas include automation to add the contact listed on the Disbursement/Requirement as a new Funding Request Role.

Another idea would be to add Funding Request Role as Lookup on the Disbursements and Requirement objects.

**Comment by Nickers3** [comment]
@sharireily, potential Atlanta Sprint discussion

**Comment by Nickers3** [comment]
Link Funding Request Roles to Requirements and Disbursements. Requirements has a Contact Lookup. Contacts linked here should also be Funding Request Roles, create/change functionality to eliminate duplicate entry and potential for data discrepancy. Financial Managers should be connected to Disbursements, create functionality to link specific Contacts/Roles to Disbursements

**Comment by sharireily** [comment]
Close out as an issue for now with reasoning... 
reasoning 
1. Adding complexity without benefit 
2. Not enough proper use cases . 

Can reopen if actual use cases become apparent.
